package view;

import controller.ReceiveAnswerButtonController;
import controller.SaveAnswersController;
import controller.StartServerButtonController;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Utils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author THARU
 */
public class MainWindow extends javax.swing.JFrame {

    StartServerButtonController broadcastController;
    ReceiveAnswerButtonController unicastController;
    /**
     * Creates new form 
     */
    public MainWindow() {
        super("Soft Clicker - Dept. of Computer Science and Engineering, University of Moratuwa");
        initComponents();   
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("cse.jpg")));
        broadcastController = new StartServerButtonController();
        unicastController = new ReceiveAnswerButtonController(this);
        startServerButton.setEnabled(false);
        receiveAnswersButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startServerButton = new javax.swing.JButton();
        receiveAnswersButton = new javax.swing.JButton();
        sumaryButton = new javax.swing.JButton();
        count = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        questionNo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        startServerButton.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        startServerButton.setText("Start Server");
        startServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonActionPerformed(evt);
            }
        });

        receiveAnswersButton.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        receiveAnswersButton.setText("Receive Answers");
        receiveAnswersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveAnswersButtonActionPerformed(evt);
            }
        });

        sumaryButton.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        sumaryButton.setText("Summary");
        sumaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaryButtonActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        count.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logoUoM.png"))); // NOI18N

        questionNo.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        questionNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     Question 01", "     Question 02", "     Question 03", "     Question 04", "     Question 05", "     Question 06", "     Question 07", "     Question 08", "     Question 09", "     Question 10" }));
        questionNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sumaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveAnswersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(questionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(receiveAnswersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sumaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerButtonActionPerformed
    
        if(startServerButton.getText().equalsIgnoreCase("Start Server")){
            if(!broadcastController.isBroadcastSeverAlive()){
                broadcastController.stopBroadcastSever();
                broadcastController.startBroadcastSever();               
            }
            startServerButton.setText("Stop Server");
            receiveAnswersButton.setEnabled(true);
        }else{
            if(broadcastController.isBroadcastSeverAlive()){
                broadcastController.stopBroadcastSever();
            }

            if(unicastController != null && unicastController.isUnicastSeverAlive()){
                unicastController.stopUnicastSever();
            }
            
            if(!receiveAnswersButton.isEnabled()){
                final JOptionPane optionPane = new JOptionPane("save results?",
                                                        JOptionPane.QUESTION_MESSAGE,
                                                        JOptionPane.YES_NO_OPTION);
                int response = JOptionPane.showConfirmDialog(optionPane,"save results?");
                if (response == JOptionPane.YES_OPTION) {
                    SaveAnswersController s = new SaveAnswersController();
                    s.save();
                }
            }
            
            receiveAnswersButton.setEnabled(false);
            startServerButton.setText("Start Server");
        }
    }//GEN-LAST:event_startServerButtonActionPerformed

    private void sumaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaryButtonActionPerformed
        SoftClicker clicker = new SoftClicker();
        clicker.pack();
        clicker.setLocationRelativeTo(null);
        clicker.setVisible(true);
    }//GEN-LAST:event_sumaryButtonActionPerformed

    private void receiveAnswersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveAnswersButtonActionPerformed
        unicastController.startUnicastSever();
        broadcastController.stopBroadcastSever();
        receiveAnswersButton.setEnabled(false);        
        
    }//GEN-LAST:event_receiveAnswersButtonActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countActionPerformed

    private void questionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionNoActionPerformed
        startServerButton.setEnabled(true);
        Utils.setQuestionNo(questionNo.getSelectedIndex()+1);
        Utils.incrementQuestionCount();
    }//GEN-LAST:event_questionNoActionPerformed

    public JTextField getCountVariable(){
        return count;
    }
    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainWindow mainWindow = new MainWindow();
                mainWindow.setLocationRelativeTo(null);
                mainWindow.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox questionNo;
    private javax.swing.JButton receiveAnswersButton;
    private javax.swing.JButton startServerButton;
    private javax.swing.JButton sumaryButton;
    // End of variables declaration//GEN-END:variables
}
